version: '3.9'

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
      - SWARM=1
      - TASKS=1
      - INFO=1
      - EVENTS=1
      - VERSION=1
      - PING=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    restart: unless-stopped

  traefik:
    image: traefik:v3.6
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dockerproxy
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/dynamic/auth.yml:/etc/traefik/dynamic/auth.yml:ro"
      - "./traefik/letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.cativo.dev`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth@file,security-headers@file"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencryptresolver"
    networks:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`cativo.dev`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencryptresolver"
      - "traefik.http.middlewares.strip-whoami.stripprefix.prefixes=/whoami"
      - "traefik.http.routers.whoami.middlewares=strip-whoami,security-headers@file"
    networks:
      - web
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.cativo.dev`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.prometheus.middlewares=auth@file,security-headers@file"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - web
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375
      - DOZZLE_NO_ANALYTICS=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.cativo.dev`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.dozzle.middlewares=auth@file,security-headers@file"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    networks:
      - web

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: "%(protocol)s://grafana.cativo.dev"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grafana.rule=Host(`grafana.cativo.dev`)"
    - "traefik.http.routers.grafana.entrypoints=websecure"
    - "traefik.http.routers.grafana.tls.certresolver=letsencryptresolver"
    - "traefik.http.routers.grafana.middlewares=security-headers@file"
    - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  grafana-data:
    driver: local
