entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic/auth.yml
    watch: true

api:
  dashboard: true
  insecure: false

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: "cativo23.kt@gmail.com"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: {}
log:
  level: WARN

ping:
  entryPoint: web
