services:
    dozzle:
      image: amir20/dozzle
      container_name: dozzle
      restart: unless-stopped
      environment:
        - DOCKER_HOST=tcp://dockerproxy:2375
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dozzle.rule=Host(`dozzle.cativo.dev`)"
        - "traefik.http.routers.dozzle.entrypoints=websecure"
        - "traefik.http.routers.dozzle.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.dozzle.middlewares=auth@file,security-headers@file"
      networks:
        - space-server_web

networks:
  space-server_web:
    external: true
