services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375
      - DOZZLE_NO_ANALYTICS=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.cativo.dev`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.dozzle.middlewares=auth@file,security-headers@file"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    networks:
      - space-server_web

networks:
  space-server_web:
    external: true
